# Generated by Django 4.0.6 on 2022-07-15 10:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='name',
        ),
        migrations.AddField(
            model_name='brand',
            name='Brand',
            field=models.CharField(default='BMW', help_text='The company name of the cars', max_length=128, validators=[django.core.validators.MinLengthValidator(4, 'minimum 4 chars')]),
        ),
        migrations.AddField(
            model_name='cars',
            name='engine',
            field=models.CharField(default='--', max_length=50),
        ),
        migrations.AddField(
            model_name='cars',
            name='exterior_color',
            field=models.CharField(default='--', max_length=50),
        ),
        migrations.AddField(
            model_name='cars',
            name='fuel_type',
            field=models.CharField(choices=[('gas', 'Gasoline'), ('diesel', 'Diesel'), ('hybrid', 'Hybrid'), ('electric', 'Electric'), ('other', 'Other')], default='gas', max_length=100),
        ),
        migrations.AddField(
            model_name='cars',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cars',
            name='style',
            field=models.CharField(choices=[('car', 'Car'), ('suv', 'SUV'), ('truck', 'Pickup Truck'), ('van', 'Minivan')], default='car', max_length=20),
        ),
        migrations.AddField(
            model_name='cars',
            name='tlike',
            field=models.CharField(choices=[('5', 'отлично'), ('4', 'хорошо'), ('3', 'нормально'), ('2', 'плохо'), ('1', 'очень плохо')], default='5', max_length=20),
        ),
        migrations.AddField(
            model_name='cars',
            name='year',
            field=models.IntegerField(default=2020),
        ),
    ]
