# Generated by Django 4.0.6 on 2022-07-15 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_remove_brand_name_brand_brand_cars_engine_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars',
            name='exterior_color',
        ),
        migrations.AddField(
            model_name='cars',
            name='color',
            field=models.CharField(choices=[('black', 'black'), ('white', 'white'), ('red', 'red'), ('yellow', 'yellow'), ('green', 'green')], default='gas', max_length=20),
        ),
        migrations.AlterField(
            model_name='cars',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='cars',
            name='style',
            field=models.CharField(choices=[('car', 'седан'), ('suv', 'SUV'), ('truck', 'Pickup Truck'), ('van', 'Minivan'), ('univ', 'универсал')], default='car', max_length=20),
        ),
    ]
