# Generated by Django 4.0.6 on 2022-07-15 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_remove_cars_exterior_color_cars_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='trating',
            field=models.CharField(choices=[('5', 'отлично'), ('4', 'хорошо'), ('3', 'нормально'), ('2', 'плохо'), ('1', 'очень плохо')], default='5', max_length=20),
        ),
        migrations.AlterField(
            model_name='cars',
            name='engine',
            field=models.CharField(choices=[('car', 'седан'), ('suv', 'SUV'), ('truck', 'Pickup Truck'), ('van', 'Minivan'), ('univ', 'универсал')], default='car', max_length=20),
        ),
        migrations.AlterField(
            model_name='cars',
            name='tlike',
            field=models.CharField(choices=[('like', 'like'), ('dislike', 'dislike')], default='like', max_length=20),
        ),
    ]
