# Generated by Django 4.0.6 on 2022-07-15 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_cars_trating_alter_cars_engine_alter_cars_tlike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars',
            name='engine',
        ),
    ]
