# Generated by Django 4.0.6 on 2022-07-15 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_remove_cars_engine'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='engine',
            field=models.CharField(choices=[('AWD', 'All Wheels Drive'), ('FWD', 'Front Wheels Drive'), ('RWD', 'Rear Wheels Drive'), ('4*4', '4*4'), ('other', 'Other')], default='AWD', max_length=20),
        ),
    ]
