# Generated by Django 4.0.6 on 2022-07-16 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_cars_engine'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cars',
            old_name='tlike',
            new_name='_like',
        ),
        migrations.RenameField(
            model_name='cars',
            old_name='trating',
            new_name='_rating',
        ),
    ]
