# Generated by Django 4.0.6 on 2022-07-16 03:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_rename_tlike_cars__like_rename_trating_cars__rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cars',
            old_name='_like',
            new_name='i_like',
        ),
        migrations.RenameField(
            model_name='cars',
            old_name='_rating',
            new_name='i_rating',
        ),
        migrations.AlterField(
            model_name='brand',
            name='Brand',
            field=models.CharField(default='BMW', help_text='The company name of the cars', max_length=128, validators=[django.core.validators.MinLengthValidator(3, 'minimum 3 chars')]),
        ),
    ]
