# Generated by Django 4.0.6 on 2022-07-16 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_rename__like_cars_i_like_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cars',
            options={'ordering': ['id']},
        ),
    ]
