# Generated by Django 4.0.6 on 2022-07-16 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_alter_cars_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cars',
            options={'ordering': ['-id']},
        ),
    ]
