# Generated by Django 4.0.6 on 2022-07-17 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0011_alter_brand_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cars',
            options={'ordering': ['-id', '-brand']},
        ),
    ]
