# Generated by Django 4.0.6 on 2022-07-21 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0021_alter_cars_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='image',
            field=models.ImageField(blank=True, default='images/bmw.jpg', null=True, upload_to='images/'),
        ),
    ]
