# Generated by Django 4.0.6 on 2022-07-21 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0022_alter_cars_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='image',
            field=models.ImageField(blank=True, default='images/bmw.gif', null=True, upload_to='images/'),
        ),
    ]
