# Generated by Django 4.0.6 on 2022-07-21 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0023_brand_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.ImageField(blank=True, default='images/bmw-logo.jpeg', null=True, upload_to='images/'),
        ),
    ]
