# Generated by Django 4.0.6 on 2022-07-21 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0024_alter_brand_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['id', 'Brand']},
        ),
        migrations.AlterModelOptions(
            name='cars',
            options={'ordering': ['id', 'brand']},
        ),
    ]
